---
title: "Harmony batch correction"
output: html_document
---

```{r}
library(Seurat)
library(cowplot)
library(harmony)
library(dplyr)
library(ggplot2)
```

load data


```{r}
load("CM1_2.rds")
load("CM3_4.rds")
load("CM5.rds")
load("CR13_14.rds")
load("CR15_16.rds")
load("CR17_18.rds")
load("CS7_8.rds")
load("CS9_10.rds")
load("CS11_12.rds")
```

Merge data

```{r}
covid=merge(x=CM1_2, y=c(CM3_4, CM5, CR13_14, CR15_16, CR17_18, CS7_8, CS9_10, CS11_12))
```

preprocessing for normalization, scaling, run PCA

```{r}
covid<- covid%>%
  Seurat::NormalizeData(verbose = T) %>%
  FindVariableFeatures(selection.method = "vst", nfeatures = 5000) %>% 
  ScaleData(verbose = T, features = rownames(covid)) %>% 
  RunPCA(pc.genes = covid@var.genes, npcs = 20, verbose = T)
```

run harmony for batch correction
```{r}
covid<- covid%>% 
  RunHarmony("patient", plot_convergence = TRUE)
```

run UMAP dimension reduction and cluster the cells

```{r}
covid<- covid%>% 
  RunUMAP(reduction = "harmony", dims = 1:20) %>% 
  FindNeighbors(reduction = "harmony", dims = 1:20) %>% 
  FindClusters(resolution = 0.4) %>% 
  identity()
DimPlot(covid, reduction="umap", label=T)
DimPlot(covid, reduction="umap", group.by="group")

```

save data

```{r}
save(covid, file="covidharmony.rds")
```























